
export const UPDATE_API_REQUEST_LOADING = "UPDATE_API_REQUEST_LOADING";
export const LOGOUT = 'LOGOUT'
export const UPDATE_USER_SESSION = 'LOGIN'
export const UPDATE_API_REQUEST_ERROR = "UPDATE_API_REQUEST_ERROR";